<a href="https://colab.research.google.com/github/MartiRudari/Imaging-Beyond-Consumer-Cameras-PS/blob/main/NeRF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!mkdir -p /content/drive/MyDrive/nerfstudio_colab

In [ ]:
%cd /content/drive/MyDrive/nerfstudio_colab

/content/drive/MyDrive/nerfstudio_colab


In [ ]:
!git clone https://github.com/yenchenlin/nerf-pytorch.git

Cloning into 'nerf-pytorch'...
remote: Enumerating objects: 461, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 461 (delta 0), reused 0 (delta 0), pack-reused 459 (from 2)
Receiving objects: 100% (461/461), 3.99 MiB | 7.35 MiB/s, done.
Resolving deltas: 100% (263/263), done.


In [ ]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install imageio imageio-ffmpeg matplotlib configargparse tqdm

Looking in indexes: https://download.pytorch.org/whl/cu118


In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4


In [ ]:
%cd /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch

/content/drive/MyDrive/nerfstudio_colab/nerf-pytorch


CHAIR

In [ ]:
!ls /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/chair
!ls /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/chair/train

test   transforms_test.json   transforms_val.json
train  transforms_train.json  val
r_0.png   r_21.png  r_33.png  r_45.png	r_57.png  r_69.png  r_80.png  r_92.png
r_10.png  r_22.png  r_34.png  r_46.png	r_58.png  r_6.png   r_81.png  r_93.png
r_11.png  r_23.png  r_35.png  r_47.png	r_59.png  r_70.png  r_82.png  r_94.png
r_12.png  r_24.png  r_36.png  r_48.png	r_5.png   r_71.png  r_83.png  r_95.png
r_13.png  r_25.png  r_37.png  r_49.png	r_60.png  r_72.png  r_84.png  r_96.png
r_14.png  r_26.png  r_38.png  r_4.png	r_61.png  r_73.png  r_85.png  r_97.png
r_15.png  r_27.png  r_39.png  r_50.png	r_62.png  r_74.png  r_86.png  r_98.png
r_16.png  r_28.png  r_3.png   r_51.png	r_63.png  r_75.png  r_87.png  r_99.png
r_17.png  r_29.png  r_40.png  r_52.png	r_64.png  r_76.png  r_88.png  r_9.png
r_18.png  r_2.png   r_41.png  r_53.png	r_65.png  r_77.png  r_89.png
r_19.png  r_30.png  r_42.png  r_54.png	r_66.png  r_78.png  r_8.png
r_1.png   r_31.png  r_43.png  r_55.png	r_67.png  r_79.png  r_90.png
r_20.png  r_3

In [ ]:
!python /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/run_nerf.py \
    --config /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/configs/chair.txt \
    --datadir /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/chair \
    --i_weights 500 \
    --i_print 100

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1275: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, np.float64(555.5555155968841)] /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/chair
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 1

In [ ]:
!python run_nerf.py \
  --config configs/chair.txt \
  --datadir /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/chair \
  --basedir /content/drive/MyDrive/nerfstudio_colab/logs \
  --expname blender_paper_chair \
  --render_only \
  --i_weights 12500



/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1275: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, np.float64(555.5555155968841)] /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/chair
Found ckpts ['/content/drive/MyDrive/nerfstudio_colab/logs/blender_paper_chair/000500.tar', '/content/drive/MyDrive/nerfstudio_colab/logs/blender_paper_chair/001000.tar', '/content/drive/MyDrive/nerfstudio_colab/logs/blender_paper_chair/001500.tar', '/content/drive/MyDrive/nerfstudio_colab/logs/blender_paper_chair/002000.tar', '/content/drive/MyDrive/nerfstudio_colab/logs/blender_paper_chair/002500.tar', '/content/drive/MyDrive/nerfstudio_colab/logs/blender_paper_chair/003000.tar', '/content/drive/MyD

*TREX*

In [ ]:
!ls /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/trex/


colmap_output.txt  images    images_8	       sparse
database.db	   images_4  poses_bounds.npy


In [ ]:
!apt-get update
!apt-get install -y imagemagick


Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading packag

In [ ]:
!ls /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/configs

chair.txt  ficus.txt	 horns.txt   lego.txt	      mic.txt	   ship.txt
drums.txt  flower.txt	 hotdog.txt  llff_config.txt  orchids.txt  trex.txt
fern.txt   fortress.txt  leaves.txt  materials.txt    room.txt


In [ ]:
!python /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/run_nerf.py \
  --config /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/configs/fern.txt \
  --datadir /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/trex \
  --basedir /content/drive/MyDrive/nerfstudio_colab/logs \
  --expname trex_llff \
  --i_weights 500 \
  --i_print 100

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1275: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Loaded image data (378, 504, 3, 55) [378.         504.         416.23374465]
Loaded /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/trex 14.611281520672364 128.97241851887296
recentered (3, 5)
[[ 1.0000000e+00 -8.9834629e-10 -9.6571471e-09  6.5023249e-09]
 [ 8.9834634e-10  1.0000000e+00  7.2768644e-09 -6.6377899e-09]
 [ 9.6571471e-09 -7.2768644e-09  1.0000000e+00  4.0639531e-10]]
Data:
(55, 3, 5) (55, 378, 504, 3) (55, 2)
HOLDOUT view is 20
Loaded llff (55, 378, 504, 3) (120, 3, 5) [378.      504.      416.23373] /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/trex
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts []
get rays
done

In [ ]:
!mkdir -p /content/drive/MyDrive/nerfstudio_colab/logs/trex_llff/ckpts
!mv /content/drive/MyDrive/nerfstudio_colab/logs/trex_llff/021000.tar \
      /content/drive/MyDrive/nerfstudio_colab/logs/trex_llff/ckpts/


In [ ]:
!python /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/run_nerf.py \
    --config /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/configs/fern.txt \
    --datadir /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/trex \
    --basedir /content/drive/MyDrive/nerfstudio_colab/logs \
    --expname trex_llff \
    --i_weights 21000 \
    --render_only

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1275: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Loaded image data (378, 504, 3, 55) [378.         504.         416.23374465]
Loaded /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/trex 14.611281520672364 128.97241851887296
recentered (3, 5)
[[ 1.0000000e+00 -8.9834629e-10 -9.6571471e-09  6.5023249e-09]
 [ 8.9834634e-10  1.0000000e+00  7.2768644e-09 -6.6377899e-09]
 [ 9.6571471e-09 -7.2768644e-09  1.0000000e+00  4.0639531e-10]]
Data:
(55, 3, 5) (55, 378, 504, 3) (55, 2)
HOLDOUT view is 20
Loaded llff (55, 378, 504, 3) (120, 3, 5) [378.      504.      416.23373] /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/trex
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['/content/drive

LEGO

In [ ]:
!ls /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/lego
!ls /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/lego/train

test   transforms_test.json   transforms_val.json
train  transforms_train.json  val
r_0.png   r_21.png  r_33.png  r_45.png	r_57.png  r_69.png  r_80.png  r_92.png
r_10.png  r_22.png  r_34.png  r_46.png	r_58.png  r_6.png   r_81.png  r_93.png
r_11.png  r_23.png  r_35.png  r_47.png	r_59.png  r_70.png  r_82.png  r_94.png
r_12.png  r_24.png  r_36.png  r_48.png	r_5.png   r_71.png  r_83.png  r_95.png
r_13.png  r_25.png  r_37.png  r_49.png	r_60.png  r_72.png  r_84.png  r_96.png
r_14.png  r_26.png  r_38.png  r_4.png	r_61.png  r_73.png  r_85.png  r_97.png
r_15.png  r_27.png  r_39.png  r_50.png	r_62.png  r_74.png  r_86.png  r_98.png
r_16.png  r_28.png  r_3.png   r_51.png	r_63.png  r_75.png  r_87.png  r_99.png
r_17.png  r_29.png  r_40.png  r_52.png	r_64.png  r_76.png  r_88.png  r_9.png
r_18.png  r_2.png   r_41.png  r_53.png	r_65.png  r_77.png  r_89.png
r_19.png  r_30.png  r_42.png  r_54.png	r_66.png  r_78.png  r_8.png
r_1.png   r_31.png  r_43.png  r_55.png	r_67.png  r_79.png  r_90.png
r_20.png  r_3

In [ ]:
!python /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/run_nerf.py \
    --config /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/configs/lego.txt \
    --datadir /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/lego \
    --i_weights 500 \
    --i_print 100

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1275: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, np.float64(555.5555155968841)] /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/lego
Found ckpts ['./logs/blender_paper_lego/000500.tar', './logs/blender_paper_lego/001000.tar', './logs/blender_paper_lego/001500.tar', './logs/blender_paper_lego/002000.tar', './logs/blender_paper_lego/002500.tar']
Reloading from ./logs/blender_paper_lego/002500.tar
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 6

In [ ]:
!python /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/run_nerf.py \
  --config /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/configs/lego.txt \
  --datadir /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/lego \
  --basedir /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/logs \
  --expname blender_paper_lego \
  --render_only \
  --i_weights 14500


/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1275: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, np.float64(555.5555155968841)] /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/lego
Found ckpts ['/content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/logs/blender_paper_lego/000500.tar', '/content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/logs/blender_paper_lego/001000.tar', '/content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/logs/blender_paper_lego/001500.tar', '/content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/logs/blender_paper_lego/002000.tar', '/content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/logs/blender_paper_lego/002500.tar', '/content/drive/MyDrive/nerfstudio_cola

PINE 360

In [ ]:
!python /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/run_nerf.py \
  --config /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/configs/pine.txt \
  --i_weights 500 \
  --i_print 100

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1275: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Loaded image data (363, 484, 3, 99) [363.         484.         418.28039153]
Loaded /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/nerf_real_360/pinecone 2.653367290686518 31.696677997900455
recentered (3, 5)
[[ 1.0000000e+00  6.3540267e-10  2.5274190e-08  3.7328160e-08]
 [-6.3540112e-10  1.0000000e+00 -6.1781350e-08  4.8165369e-09]
 [-2.5274192e-08  6.1781350e-08  1.0000000e+00 -5.0272604e-08]]
Data:
(99, 3, 5) (99, 363, 484, 3) (99, 2)
HOLDOUT view is 97
Loaded llff (99, 363, 484, 3) (120, 3, 5) [363.     484.     418.2804] /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/nerf_real_360/pinecone
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 

In [ ]:
!python /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/run_nerf.py \
  --config /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/configs/pine.txt \
  --datadir /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/nerf_real_360/pinecone \
  --basedir /content/drive/MyDrive/nerfstudio_colab/logs \
  --expname pine_paper \
  --render_only \
  --i_weights 47000


/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1275: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Loaded image data (363, 484, 3, 99) [363.         484.         418.28039153]
Loaded /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/nerf_real_360/pinecone 2.653367290686518 31.696677997900455
recentered (3, 5)
[[ 1.0000000e+00  6.3540267e-10  2.5274190e-08  3.7328160e-08]
 [-6.3540112e-10  1.0000000e+00 -6.1781350e-08  4.8165369e-09]
 [-2.5274192e-08  6.1781350e-08  1.0000000e+00 -5.0272604e-08]]
Data:
(99, 3, 5) (99, 363, 484, 3) (99, 2)
HOLDOUT view is 97
Loaded llff (99, 363, 484, 3) (120, 3, 5) [363.     484.     418.2804] /content/drive/MyDrive/nerfstudio_colab/nerf-pytorch/nerf_real_360/pinecone
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 